### DISCUSSION TITLE
How to add a tutorial to the ecco hackweek book

### DISCUSSION THREAD

**Discussion by ifenty** [ECCO-Hackweek/ecco-2024#35] [Show and tell]
Adding tutorial to the ecco hackweek book requires a few steps.  As of now, I can only get jupyter notebook (*.ipynb) files to work.  The *ipynb* files are converted to html by [jupyter-book](https://jupyterbook.org/en/stable/intro.html)

Three steps for adding tutorials
1. Adding new tutorial files to the GitHub repository
1. Updating the "book" table of contents
1. Creating or updating the landing page (\*index.md) for the 'chapter' of the new tutorial(s)

## Adding new tutorial files to the GitHub repository

1. git clone the ecco-2024 repo
1. create a new branch, something like: ```git checkout -b my_book_edits``` 
1. navigate to ```ecco-2024/book/tutorials```
1. if the tutorial is for a new 'chapter' (subject) then make a new subdirectory, e.g., 
```ecco-2024/book/tutorials/myNewChapter```
1. copy your new Jupyter tutorial notebook(s) to the new subdirectory
1. add the new subdirectory and new tutorial file(s) to your local git branch. From the ```ecco-2024/book/tutorials/``` directory:
```
     git add myNewChapter/new_tutorial_1.ipynb
     git add myNewChapter/new_tutorial_2.ipynb
     ...
     git add myNewChapter/new_tutorial_n.ipynb
     git commit -m 'added new tutorials about X'
```

Note: the notebooks you add will not be 're-executed' when the book compiles, they will be converted to html.

## Updating the "book" table of contents

After adding the tutorial notebook files to the repository, you have to update the book 'table of contents' so that the tutorials can be included when the book compiles.

### Structure of the Table of Contents yaml

The event book has a **Table of Contents** file [book/_toc.yml](book/_toc.yml) which defines how the book is organized.  **Tutorials** are under the 'caption' *Tutorials*.  

```
# Table of content
# Learn more at https://jupyterbook.org/customize/toc.html
root: intro
format: jb-book
parts:
- caption: Details
  chapters:
    - file: logistics
    - title: Schedule
      url: https://ecco-hackweek.github.io/ecco-2024/index.html?jump_to=schedule
    - title: Team
      url: https://ecco-hackweek.github.io/ecco-2024/index.html?jump_to=team
    - file: CoC
- caption: Preparation
  chapters:
    - file: preliminary/index
    - file: preliminary/checklist
    - file: preliminary/git
- caption: Tutorials
  chapters:
    - file:  tutorials/oss_tutorial_index
      sections:
        - file: tutorials/example/tutorial-notebook
        - file: tutorials/oss_tut/oss_initial_repo
    - file:  tutorials/pcluster_tutorial_index
      sections:
        - file: tutorials/pcluster/pcluster-login
- caption: Projects
  chapters:
    - file: projects/index
- caption: Reference
  chapters:
    - file: reference/glossary
    - file: reference/bibliography
    - file: reference/questions
```

Let's look at the 'Tutorials' block in detail:

```
- caption: Tutorials
  chapters:
    - file:  tutorials/oss_tutorial_index
      sections:
        - file: tutorials/example/tutorial-notebook
        - file: tutorials/oss_tut/oss_initial_repo
    - file:  tutorials/pcluster_tutorial_index
      sections:
        - file: tutorials/pcluster/pcluster-login
```

The next line after ```caption: Tutorials``` provides for different 'chapters' . Each 'chapter' is defined by a landing page file (e.g., ```tutorials/oss_tutorial_index.md``` and ```tutorials/pcluster_tutorial_index.md```) in the example above.  

> Note that the ```*.md``` (markdown) extension of the chapter landing page files is *not* included in the yaml (I don't know why).  

What is the title of the chapter?  The chapter title is provided by the **top-level section header** of the landing page markdown file. For example, the title of the 'chapter' for the first file (tutorials/oss_tutorial_index.md) is ```# OSS Tutorials```, as below. Therefore, the book will create a 'chapter' called *OSS tutorials*.  From [oss_tutorial_index.md](book/tutorials/oss_tutorial_index.md)
```
# OSS Tutorials 

[...]
```

The 'sections' block of the yaml tells the book where the tutorial notebook files are located using relative paths.
```
chapters:
    - file:  tutorials/oss_tutorial_index
      sections:
        - file: tutorials/example/tutorial-notebook
        - file: tutorials/oss_tut/oss_initial_repo
```

> Note: the ```*.ipynb``` (jupyter notebook) extension of the tutorial files is *not* included in the yaml.

### Adding a new tutorial chapter 
1. create a landing page index.md file for your new chapter. The chapter name must be defined in the top-level section header, like ```# My New Chapter```.  You can add links to your new tutorials in the landing page.  See [this example](book/tutorials/oss_tutorial_index.md)
2. add a new file/section block to the ```_toc.yml```  for your new chapter
3. add entries new tutorial files under the 'section' block.
```
chapters:
    - file:  tutorials/oss_tutorial_index
      sections:
        - file: tutorials/example/tutorial-notebook
        - file: tutorials/oss_tut/oss_initial_repo
    - file:  tutorials/myNewChapter_tutorial_index
      sections:
        - file: tutorials/myNewChapter/new_tutorial_1.ipynb
        - file: tutorials/myNewChapter/new_tutorial_2.ipynb
        [...]
        - file: tutorials/myNewChapter/new_tutorial_n.ipynb   
```

### Adding tutorials to an existing chapter 
1. update the landing page index.md file for the existing chapter. You can add links to your new tutorials in the landing page.  See [this example](book/tutorials/oss_tutorial_index.md)
3. add entires for the new tutorial files under the 'section' block of  the ```_toc.yml```.
```
chapters:
    - file:  tutorials/oss_tutorial_index
      sections:
        - file: tutorials/example/tutorial-notebook
        - file: tutorials/oss_tut/oss_initial_repo
    - file:  tutorials/myNewChapter_tutorial_index
      sections:
        - file: tutorials/myNewChapter/new_tutorial_1.ipynb
        - file: tutorials/myNewChapter/new_tutorial_2.ipynb
        [...]
        - file: tutorials/myNewChapter/new_tutorial_n.ipynb   
```

Finally, git add/commit the changes to the ```_toc.yml```.  From the ecco-2024/book directory:

```
git add _toc.yml
git commit -m 'added entries for my new tutorials'
```

## Creating or updating the landing page (\*index.md) for the 'chapter' of the new tutorial(s)

As described above, the landing page for each chapter is a markdown file. The top-level section header defines the chapter name. 

In the example below there is a table with entries for each tutorial in the chapter. The table provides a tutorial name, a link to the file (relative path, *INCLUDE* ipynb extension), and a brief description of the topics covered.  

> The table is optional. The book will compile without it.  However, I think it is a good idea to give people a high-level idea of what is in each tutorials.

```# OSS Tutorials 

Hackweek tutorials are learning-oriented and guide participants through a step-wise process with a meaningful outcome. If you are putting together a new tutorial for this event, refer to our [Hackweek Guidebook](https://guidebook.hackweek.io/training/tutorials/index.html).

Below you'll find a table keeping track of all tutorials presented at this event:

| Tutorial | Topics | Datasets |  Recording Link |
| -  | - | - |  - |
| [OSS initial repo setup](./oss_tut/oss_initial_repo.ipynb) | Fork and Clone the ECCO-v4-Python Tutorial repository | n/a |  Not recorded |
| [Example Notebook](./example/tutorial-notebook.ipynb) | Jupyter Book formatting, ipyleaflet | n/a |  Not recorded |
```

When adding tutorials to an existing chapter, you can update the table of the chapter's landing markdown page. To  creating a new chapter, just copy and modify an existing chapter landing page.

From the ```ecco-2024/book/tutorials``` directory
```
git add myNewChapter_tutorial_index.md
git commit -m 'added (or updated) the the chapter tutorial index landing page'
```

When finished, don't forget to push your changes and make a pull request.
```
git push origin my_book_edits
```
